version: '3.3'

services:
    web:
      image: 'gitlab-custom:latest'
      restart: always
      # hostname: 'gitlab.example.com'
      # environment:
      #   GITLAB_OMNIBUS_CONFIG: |
      #     external_url 'https://gitlab.example.com'
      ports:
        - '80:80'
        - '443:443'
        - '22:22'
      volumes:
        - '/var/data/gitlab/config:/etc/gitlab'
        - '/var/data/gitlab/logs:/var/log/gitlab'
        - '/var/data/gitlab/data:/var/opt/gitlab'
      links:
        - "postgres-db:postgres-db"
    postgres-db:
      image: postgres:13
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: secret
      restart: always
    